### ISSUE TITLE
Problem using resources in survey

### ISSUE THREAD

**Issue by SF2311** [owncloud-ops/limesurvey#117]
Hello,
I am runing a limesurvey instance using this container image.
If I try to add a resource to a new survey I get the following error:
![grafik](https://user-images.githubusercontent.com/33719441/177619789-1f0a3234-3f37-400f-a8cd-995c3dda3b9d.png)
Is this a configuration issue on my part, or is this a general problem when using this container image?
Kind Regards.

**Comment by xoxys** [comment]
Hi, thanks for reporting! I have created a PR already to fix this. Will tag a new release after CI passed.
