### ISSUE TITLE
Add pertinent *_FILE env vars

### ISSUE THREAD

**Issue by nwmcsween** [owncloud-ops/limesurvey#17]
LIME_ADMIN_PASSWORD, LIME_LDAP_BINDPW, etc could use _FILE suffixed env versions in order to allow secret usage.

**Comment by xoxys** [comment]
Thanks for your report. Keep in mind this is just a custom docker image for LimeSurvey. We are not the upstream maintainer. That said we added a custom env var handling to get the container ready to use on startup without the need of the web installer. I don't see how using a *_FILE env would help especially as the env vars are only processed by the entrypoint script, sorry.
