### ISSUE TITLE
Additional Settings in security.php

### ISSUE THREAD

**Issue by SF2311** [owncloud-ops/limesurvey#79]
During a recent update to Limesurvey version 5.3.3 two additional options were set by the update process in my security.php:
`$config['encryptionnonce']` and `$config['encryptionsecretboxkey']`.
Would it be possible to add these options to the template for `security.php`?
Or would it be better to persist this file, as apparently the upgrade process can alter it?

**Comment by xoxys** [comment]
Thanks for the hint! Both ways should work. If the file exists already because it was persisted, the container will not override it. For those who prefer env vars, I'll create a PR to add the missing options.
